import Logo from "@/components/logo";
import { ThemeToggle } from "@/components/themetoggler";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex flex-col gap-5 items-center justify-center min-h-screen py-20 relative">
      <Logo />
      {children}
      <div className="fixed bottom-10 right-10">
        <ThemeToggle />
      </div>
    </main>
  );
}
